### ISSUE TITLE
Telugu labelled data not downloadable

### ISSUE THREAD

**Issue by vasistalodagala** [Open-Speech-EkStep/ULCA-asr-dataset-corpus#3]
The download links for the Telugu labelled data (1024.93 hours) are not working.
They have probably expired now.
Please look into this issue and restore access.

**Comment by ma08** [comment]
I can confirm as well. Would appreciate if this is looked into and resolved.

**Comment by StephennFernandes** [comment]
actually if you see closely, in the URL there is a backslash missing:

```
eg:

 actual:  https://storage.googleapis.comtest_public_bucket/labelled/Telugu_BBC_News_Telugu_17-08-2021_00-57.zip
corrected: https://storage.googleapis.com/test_public_bucket/labelled/Telugu_BBC_News_Telugu_17-08-2021_00-57.zip
```
upon changing this the download works fine.

**Comment by vasistalodagala** [comment]
@StephennFernandes thanks for the info. @ma08 has mentioned over a different thread about this missing backslash, a few days after this issue has been opened. 
However, this hasn't been corrected in the links presented over the [README](https://github.com/Open-Speech-EkStep/ULCA-asr-dataset-corpus/blob/main/README.md) yet. 
Hoping that future users would have a peek into the issues section to find this solution.
Closing the issue now. Thanks!

**Comment by kruthikakr** [comment]
Hi 
Now the datalinks are not active. Not able to download any datasets. Can anyone please confirm?
